### ISSUE TITLE
Video status is still processing

### ISSUE THREAD

**Issue by hilmansakti** [yovanoc/codetube#1]
hi..

I've uploaded a video, and it show "Processing (Starting Up)" until now....

what should I do if I want to play it?

Thanks.

**Comment by yovanoc** [comment]
Hi,
So you have to well configure the .env with all services keys, and for the videos you have to let it run pho artisan queue:work to process the jobs queue

Cordialement,

YOVANOVITCH Christopher
0783263010

Le 19 mars 2017 à 05:42, hilmansakti <notifications@github.com<mailto:notifications@github.com>> a écrit :


hi..

I've uploaded a video, and it show "Processing (Starting Up)" until now....

what should I do if I want to play it?

Thanks.

**Comment by hilmansakti** [comment]
hi @chrisyoyo ..

this is my .env file

`APP_ENV=local
APP_KEY=base64:9w7JSy40S6/ntiXdvdVhvd/kyb+BHdClWnStzbW6/NQ=
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=http://localhost

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=tube_db
DB_USERNAME=root
DB_PASSWORD=root

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=database

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

PUSHER_APP_ID=
PUSHER_KEY=
PUSHER_SECRET=

S3_KEY=
S3_SECRET=
S3_REGION=
S3_DROP_BUCKET=
S3_IMAGES_BUCKET=
S3_VIDEOS_BUCKET=

ALGOLIA_APP_ID=
ALGOLIA_SECRET=`


did I miss something?

**Comment by hilmansakti** [comment]
hi @chrisyoyo 

okee.. thanks

**Comment by yovanoc** [comment]
You have to fill all S3 keys and ALGOLIA on your .env...

Cordialement,

YOVANOVITCH Christopher
0783263010

Le 21 mars 2017 à 13:41, hilmansakti <notifications@github.com<mailto:notifications@github.com>> a écrit :


hi @chrisyoyo<https://github.com/chrisyoyo>

okee.. thanks
