### ISSUE TITLE
The media could not be loaded, either because the server or network failed or because the format is not supported.

### ISSUE THREAD

**Issue by aarontanzk** [yovanoc/codetube#5]
Hi, I have uploaded my video on Homestead but it takes very long to process.

When i alter the processed column in SQL, and play the video, it gives me the above error.

Any idea how to solve this?

**Comment by yovanoc** [comment]
I think this is related to https://github.com/yovanoc/codetube/issues/4
In fact, when you upload a video it's uploaded to the drop bucket in aws. After you have to set up a webhook with Telestream or other encoding systems to encode the video and put it back in the videos bucket. But there is a bug with the job that upload videos I will take a look a this very soon
